/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pc231;

/**
 *
 * @author Marco
 */
public class PC231Simulator extends javax.swing.JFrame {

    /**
     * Creates new form PC231Simulator
     */
    public PC231Simulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        pcInput = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        programInput = new javax.swing.JTextArea();
        title = new javax.swing.JLabel();
        assembler = new javax.swing.JLabel();
        assemblerDes = new javax.swing.JLabel();
        getHex = new javax.swing.JButton();
        hexCodesLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hexOutput = new javax.swing.JTextArea();
        Simulator = new javax.swing.JLabel();
        sim231Label = new javax.swing.JLabel();
        runPC231 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        programOutput = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        hexInput = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pcInput.setBackground(new java.awt.Color(0, 0, 0));
        pcInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        programInput.setColumns(20);
        programInput.setRows(5);
        jScrollPane1.setViewportView(programInput);

        pcInput.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 340, 320));

        title.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("PC 231      Edition");
        pcInput.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        assembler.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        assembler.setForeground(new java.awt.Color(255, 255, 255));
        assembler.setText("Assembler");
        pcInput.add(assembler, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        assemblerDes.setForeground(new java.awt.Color(255, 255, 255));
        assemblerDes.setText("Insert your assembly code here");
        pcInput.add(assemblerDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        getHex.setText("Generate Hex Codes");
        getHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getHexActionPerformed(evt);
            }
        });
        pcInput.add(getHex, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 190, 50));

        hexCodesLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        hexCodesLabel.setForeground(new java.awt.Color(255, 255, 255));
        hexCodesLabel.setText("Your Hex Codes");
        pcInput.add(hexCodesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 210, -1));

        hexOutput.setEditable(false);
        hexOutput.setBackground(new java.awt.Color(204, 255, 204));
        hexOutput.setColumns(20);
        hexOutput.setRows(5);
        hexOutput.setBorder(null);
        jScrollPane3.setViewportView(hexOutput);

        pcInput.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 340, 100));

        Simulator.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        Simulator.setForeground(new java.awt.Color(255, 255, 255));
        Simulator.setText("Simulator");
        pcInput.add(Simulator, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 130, 30));

        sim231Label.setForeground(new java.awt.Color(255, 255, 255));
        sim231Label.setText("Insert Hex Codes below, then click the \"Run Program\" Button");
        pcInput.add(sim231Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        runPC231.setText("Run Program");
        runPC231.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runPC231ActionPerformed(evt);
            }
        });
        pcInput.add(runPC231, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 160, 40));

        programOutput.setBackground(new java.awt.Color(204, 255, 204));
        programOutput.setColumns(20);
        programOutput.setRows(5);
        jScrollPane4.setViewportView(programOutput);

        pcInput.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 470, 300));

        jLabel8.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PC 231 Output");
        pcInput.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 200, -1));

        hexInput.setColumns(20);
        hexInput.setRows(5);
        jScrollPane5.setViewportView(hexInput);

        pcInput.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 470, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Gold");
        pcInput.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 100, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/Marco/Classes/2016 - 2017/Spring 2017/CS 353/pcGold.png")); // NOI18N
        jLabel2.setText("jLabel2");
        pcInput.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 90));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pcInput.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 660, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pcInput, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pcInput, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getHexActionPerformed
        // TODO add your handling code here:
             
    Assembler asm = new Assembler();
    
        asm.run(programInput.getText());
        asm.cleanUp();

        asm.getHexCodes();
        hexOutput.setText(asm.toString());
        hexInput.setText(asm.toString());
        
        
    }//GEN-LAST:event_getHexActionPerformed

    private void runPC231ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runPC231ActionPerformed
        // TODO add your handling code here:
        String hexCode = hexInput.getText();
        Simulator sim231 = new Simulator(hexCode);
        sim231.runProgram();
        programOutput.setText(sim231.toString());
    }//GEN-LAST:event_runPC231ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        hexInput.setText(null);
        programOutput.setText(null);
        hexOutput.setText(null);
        programInput.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PC231Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PC231Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PC231Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PC231Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PC231Simulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Simulator;
    private javax.swing.JLabel assembler;
    private javax.swing.JLabel assemblerDes;
    private javax.swing.JButton getHex;
    private javax.swing.JLabel hexCodesLabel;
    private javax.swing.JTextArea hexInput;
    private javax.swing.JTextArea hexOutput;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel pcInput;
    private javax.swing.JTextArea programInput;
    private javax.swing.JTextArea programOutput;
    private javax.swing.JButton runPC231;
    private javax.swing.JLabel sim231Label;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
