/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twoscompliment;

import java.util.ArrayList;

/**
 *
 * @author Marco
 */
public class twosForm extends javax.swing.JFrame {

   dataManagement dm = new dataManagement();
   
   
  
    
    public twosForm() {
        initComponents();
      overFlowLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLable = new javax.swing.JLabel();
        inputA = new javax.swing.JTextField();
        inputB = new javax.swing.JTextField();
        inputLabel1 = new javax.swing.JLabel();
        inputLabel2 = new javax.swing.JLabel();
        outputA = new javax.swing.JTextField();
        outputB = new javax.swing.JTextField();
        twosLabel = new javax.swing.JLabel();
        plusLabel = new javax.swing.JLabel();
        equalsLabel = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        calcButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        overFlowLabel = new javax.swing.JLabel();
        numeralTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLable.setFont(new java.awt.Font("Phosphate", 1, 36)); // NOI18N
        titleLable.setText("Two's Complement");

        inputA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAActionPerformed(evt);
            }
        });

        inputB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBActionPerformed(evt);
            }
        });

        inputLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        inputLabel1.setText("Input 1:");

        inputLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        inputLabel2.setText("Input 2: ");

        outputA.setEditable(false);
        outputA.setBackground(new java.awt.Color(204, 204, 204));
        outputA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputAActionPerformed(evt);
            }
        });

        outputB.setEditable(false);
        outputB.setBackground(new java.awt.Color(204, 204, 204));
        outputB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputBActionPerformed(evt);
            }
        });

        twosLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        twosLabel.setForeground(new java.awt.Color(51, 51, 51));
        twosLabel.setText("Two's Compliment  Form");

        plusLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        plusLabel.setText("+");

        equalsLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        equalsLabel.setText("=");

        totalField.setEditable(false);
        totalField.setBackground(new java.awt.Color(204, 204, 204));
        totalField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 4));
        totalField.setPreferredSize(new java.awt.Dimension(8, 32));
        totalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFieldActionPerformed(evt);
            }
        });

        totalLabel.setBackground(new java.awt.Color(0, 153, 0));
        totalLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(0, 153, 51));
        totalLabel.setText("Total");

        calcButton.setText("Calulate");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        overFlowLabel.setIcon(new javax.swing.ImageIcon("/Users/Marco/Classes/2016 - 2017/Spring 2017/CS 353/Labs/twosCompliment/src/twoscompliment/overflow.png")); // NOI18N

        numeralTotal.setBackground(new java.awt.Color(204, 204, 204));
        numeralTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 4, true));
        numeralTotal.setPreferredSize(new java.awt.Dimension(8, 32));
        numeralTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeralTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(overFlowLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(inputA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(outputA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(plusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(outputB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(twosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(equalsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numeralTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exitButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(inputLabel2)
                                .addGap(0, 0, 0)
                                .addComponent(inputB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(clearButton)))
                        .addGap(131, 131, 131)
                        .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(titleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(twosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(outputA)
                            .addComponent(plusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outputB)
                            .addComponent(equalsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(inputLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(inputB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(overFlowLabel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeralTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inputAActionPerformed

    private void inputBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBActionPerformed

    private void outputAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputAActionPerformed
    
    }//GEN-LAST:event_outputAActionPerformed

    private void outputBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputBActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
       
      String userInputA = inputA.getText();
      
      String userInputB = inputB.getText();
      
     dataManagement dm = new dataManagement();
      
      
      int numInputA=  Integer.parseInt(userInputA);
      int numInputB = Integer.parseInt(userInputB);
      int numTotal = 0;
        
      ArrayList<Integer> A = dm.convertInputA(userInputA);
      ArrayList<Integer> B = dm.converInputB(userInputB);
      ArrayList<Integer> sumTotal = dm.addInputs();
      
       
      StringBuilder Ainput = new StringBuilder();
      StringBuilder Binput = new StringBuilder();
      StringBuilder totalOutput = new StringBuilder();
      
      
       //Checks to make sure there is no overflow!
       if ((numInputA > 127 || numInputB > 127 || numInputA < -128|| numInputB < -128) || (sumTotal.get(0)==404)){
           overFlowLabel.setVisible(true);
       } else {
           //Populate A inputfield
           for (int i =0; i < A.size(); i++){
           Ainput.append(A.get(i));
         }
           //Populate B inputfield
           for (int i = 0; i < B.size(); i ++){
           Binput.append(B.get(i));
          }    
           //Populate total Field 
           for (int i = 0; i < sumTotal.size(); i ++){
           totalOutput.append(sumTotal.get(i));
       }
           numTotal = dm.converOutput();
           
       }
    
       
      
      
       
           
          outputA.setText(String.valueOf(Ainput.toString()));
          outputB.setText(String.valueOf(Binput.toString()));
          totalField.setText(String.valueOf(totalOutput.toString()));
          numeralTotal.setText(String.valueOf(numTotal));
          
          
              
        
    }//GEN-LAST:event_calcButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
         String userInputA = inputA.getText();
         String userInputB = inputB.getText();
         String output  = totalField.getText();
         
         overFlowLabel.setVisible(false);
        
      ArrayList<Integer> A = dm.convertInputA(userInputA);
      ArrayList<Integer> B = dm.converInputB(userInputB);
      ArrayList<Integer> sumTotal = dm.addInputs();
      
        outputB.setText(null);
        outputA.setText(null);
        inputA.setText(null);
        A.clear();
        inputB.setText(null);
        B.clear();
        totalField.setText(null);
        sumTotal.clear();
        numeralTotal.setText(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void totalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFieldActionPerformed

    private void numeralTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeralTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeralTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(twosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(twosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(twosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(twosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new twosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel equalsLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField inputA;
    private javax.swing.JTextField inputB;
    private javax.swing.JLabel inputLabel1;
    private javax.swing.JLabel inputLabel2;
    private javax.swing.JTextField numeralTotal;
    private javax.swing.JTextField outputA;
    private javax.swing.JTextField outputB;
    private javax.swing.JLabel overFlowLabel;
    private javax.swing.JLabel plusLabel;
    private javax.swing.JLabel titleLable;
    private javax.swing.JTextField totalField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel twosLabel;
    // End of variables declaration//GEN-END:variables
}
